sync-with-github:
  before_script:
    - git config --global user.name "getindata-cicd"
    - git config --global user.email "cicd@getindata.com"
  only:
    - main
  script:
    - git remote add github https://github.com/getindata/quickstart-ml-blueprints.git
    - git fetch
    - git checkout main
    - git pull origin main
    - git pull github main
    - git status
    - git push https://getindata-cicd:$PASSWORD@gitlab.com/getindata/aa-labs/coe/quickstart-ml-blueprints.git HEAD:main
