image_embeddings:
  image_path: data/01_raw/images_128_128
  encoder: SimpleEncoder
  decoder: SimpleDecoder
  batch_size: 32
  image_size: [128, 128]
  embedding_size: 32
  num_epochs: 20
  shuffle_reconstructions: True
  save_model: False
  model_name: pl_image_embeddings
  seed: 321